# Generated by Django 4.1.7 on 2024-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='action',
            field=models.CharField(choices=[('ADD', 'ADD'), ('INPROCESS', 'INPROCESS'), ('UPDATED', 'UPDATED'), ('COMPLETE', 'COMPLETE'), ('DELETE', 'DELETE')], default='ADD', max_length=255),
        ),
    ]
